In [1]:
import sys
sys.path.insert(0, '..')
import treesearch as ts
import agents.qtree as qtree
import numpy as np
import util
from visual import GameWithConfidences
from environment import Env
from agents.random_agent import RandomAgent
from agents.human import Human
import agents.treeactivated as activated

%load_ext autoreload
%autoreload 2

In [2]:
agent = util.load_agent("current.npz", activated.TanhHidden)

In [4]:
params = {"learn_rate": .1, "rotate": True, "train_live": True, "rotate_live": True}
agent = activated.TanhHidden([16, 100, 100, 100, 100, 16], play_simulations = 20, params = params, max_queue = 300, act_mode = "search")

In [ ]:
agent.self_play(1000, 50, train = True, save_every = 2, save_name = "agents/saves/current_large.npz")

In [18]:
e = Env(4)
r = RandomAgent(e)
h = Human()
agent.act_mode = "search"
agent.play_simulations = 20
gui = GameWithConfidences(e, agent, agent, -1, show_confidences = False)

SystemExit: 

C:\Users\abeol\Anaconda3\envs\Deep-Notakto\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [24]:
x = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 1, 1]
])
print("PLAYER #{}".format(np.int32((np.sum(x) % 2) + 1)))
print(agent.value(x))
print(agent.get_Q(x))

PLAYER #1
1.0
[[  1.52855471e-01   6.43253998e-07   1.27920315e-01   1.04979838e-08]
 [  1.44402906e-10   1.90623160e-02   2.43166126e-02   2.90129520e-09]
 [  1.14728055e-05   3.71068297e-03   1.88942123e-02   3.28234851e-01]
 [  2.81776013e-13   6.54530525e-02   2.59540260e-01   5.35258560e-10]]
