In [1]:
import sys
sys.path.insert(0, '..')
import treesearch as ts
import agents.qtree as qtree
from environment import Env
import numpy as np
from importlib import reload
from util import rotate, array_in_list
from copy import copy

In [2]:
%load_ext autoreload
%autoreload 2

In [26]:
agent = qtree.QTree([9, 9], name = "QTreeTrials")
state =  np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])
root = ts.GuidedNotaktoNode(state = state, network = agent)
#root = ts.NotaktoNode(state)
e = Env(3)
ts.guidedsearch(root, iterations = 4)
#n = ts.self_play(root, iterations = 10)
#print(n)

In [29]:
ts.guidedsearch(root, iterations = 100)

In [30]:
root.display()

Node (Player 1, Winner 0)
Visits : 196, Total Value : 114.776395327, and Prior : 0.111111
Upper Confidence Bound : 0.596760796757
State:  [[0 1 0]
	 [0 0 0]
	 [0 0 0]]

Node (Player 1, Winner 0)
Visits : 4, Total Value : 0.530565522611, and Prior : 0.111111
Upper Confidence Bound : 0.195495317227
State:  [[0 0 0]
	 [0 1 0]
	 [0 0 0]]

Node (Player 1, Winner 0)
Visits : 4, Total Value : -0.0346848294139, and Prior : 0.111111
Upper Confidence Bound : 0.0541827292203
State:  [[1 0 0]
	 [0 0 0]
	 [0 0 0]]



In [18]:
root[0][0].display()

Node (Player 1, Winner 0)
Visits : 1, Total Value : -1, and Prior : 0.131468
Upper Confidence Bound : -0.907038097622
State:  [[1 1 0]
	 [0 1 0]
	 [0 0 0]]

Node (Player 1, Winner 0)
Visits : 4, Total Value : 2, and Prior : 0.0891321
Upper Confidence Bound : 0.550420746918
State:  [[0 1 0]
	 [1 1 0]
	 [0 0 0]]

Node (Player 1, Winner 0)
Visits : 107, Total Value : 107, and Prior : 0.0968373
Upper Confidence Bound : 1.01311673133
State:  [[0 1 0]
	 [0 1 0]
	 [1 0 0]]



In [ ]:
c = root[-1]

In [ ]:
(c.w / c.n)