In [1]:
import sys
sys.path.insert(0, '..')
import treesearch as ts
import numpy as np
from importlib import reload
from util import rotate, array_in_list
import agents.random_agent as rp
from environment import Env
from copy import copy

In [35]:
_ = reload(ts)

In [37]:
# root = ts.NotaktoNode(np.zeros([4,4], dtype = np.int32), None, None)
e = Env(3)
#root = ts.load("full.tree", False)
root = ts.NotaktoNode(copy(e.board))
root = ts.search(root, iterations = 10)
opponent = rp.RandomAgent(e)
p = ts.play(e, root, opponent, True)

------------
ROOT NODE at 10 (P1 : 7 wins)
Node (Player 1, Winner 0)
Wins : 5 and Visits : 5
State:  [[1 0 0]
	 [0 0 0]
	 [0 0 0]]]
^^^^^^^^^^^^

X O O 
O O O 
O O O 


X O O 
O O O 
O X O 

------------
Node (Player 2, Winner 0)
Wins : 0 and Visits : 0
State:  [[1 0 0]
	 [0 0 0]
	 [0 0 1]]]
Node (Player 1, Winner 0)
Wins : 0 and Visits : 0
State:  [[1 0 1]
	 [0 0 0]
	 [0 0 1]]]
^^^^^^^^^^^^

X X O 
O O O 
O X O 


X X O 
O O X 
O X O 

------------
Node (Player 2, Winner 0)
Wins : 0 and Visits : 0
State:  [[1 0 1]
	 [1 0 0]
	 [0 0 1]]]
Node (Player 1, Winner 0)
Wins : 0 and Visits : 0
State:  [[1 0 1]
	 [1 0 0]
	 [0 1 1]]]
^^^^^^^^^^^^

X X O 
O O X 
O X O 

Node (Player 1, Winner 0)
Wins : 0 and Visits : 0
State:  [[1 0 1]
	 [1 0 0]
	 [0 1 1]]]


IndexError: Unvisited list is empty

In [ ]:
p

In [ ]:
p.state