In [4]:
import sys
sys.path.insert(0, '..')
import treesearch as ts
import numpy as np
from importlib import reload

In [487]:
_ = reload(ts)

In [509]:
n = ts.search(3, 1)

In [510]:
n.display_children()

Node
Wins : 0 and Visits : 1
State:  [[0 0 0]
	 [0 0 0]
	 [0 1 0]]]



In [499]:
n

Node
Wins : 0 and Visits : 1
State:  [[0 0 0]
	 [0 0 0]
	 [0 0 0]]]