In [1]:
import numpy as np
from copy import copy
import tensorflow as tf
from importlib import reload
from random import randint
import matplotlib.pyplot as plt

import environment as env
import agent
import agents.random_agent as ra
import agents.q_no_hidden as qnh

In [2]:
reload(env)
reload(agent)
reload(ra)
reload(qnh)

<module 'agents.q_no_hidden' from 'C:\\Users\\abeol\\Git\\Deep-Notakto\\deepnotakto\\agents\\q_no_hidden.py'>

In [9]:
a1 = qnh.QNoHidden(3)
w1 = a1.session.run(a1.w)
a2 = ra.RandomAgent()
for i in range(1000):
    e = env.Env(3)
    e.play_cvc(a1, a2, False)
print(np.abs(w1 - a1.session.run(a1.w)))

C:\Users\abeol\Git\Deep-Notakto\deepnotakto\environment.py:72: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if board == None:


[[  2.00126190e+02   2.00085236e+02   1.08661636e+02   2.00142029e+02
    1.52874817e+02   1.99759262e+02   1.31861847e+02   1.99835251e+02
    2.00028320e+02]
 [  0.00000000e+00   1.99844223e+02   2.00528564e+01   0.00000000e+00
    0.00000000e+00   2.00082382e+02   0.00000000e+00   0.00000000e+00
    2.00028320e+02]
 [  0.00000000e+00   0.00000000e+00   2.01715866e+02   0.00000000e+00
    2.87536106e+01   0.00000000e+00   6.97505722e+01   0.00000000e+00
    0.00000000e+00]
 [  2.00126190e+02   0.00000000e+00   2.00528564e+01   2.00142029e+02
    0.00000000e+00   0.00000000e+00   1.05402622e+01   0.00000000e+00
    0.00000000e+00]
 [  2.00126190e+02   0.00000000e+00   9.30542450e+01   0.00000000e+00
    2.01564407e+02   1.82344198e-01   3.97129860e+01   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    2.87536106e+01   2.00082382e+02   3.16094170e+01   0.00000000e+00
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.

In [4]:
e = env.Env(3)
e.play_hvc(a1, False)

C:\Users\abeol\Git\Deep-Notakto\deepnotakto\environment.py:72: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if board == None:



O O O 
O O O 
O O O 


O O O 
X O O 
O O O 

Player 2
Next Piece: exit


False

In [11]:
e = env.Env(3)
print(np.reshape(a1.get_Q(e.observe()), [3, 3]))

[[-198.80102539 -201.3250885  -108.58683014]
 [-198.19668579  -11.51227188 -199.64823914]
 [-133.5317688  -200.72920227 -199.79154968]]


In [12]:
a1.act(e)

C:\Users\abeol\Git\Deep-Notakto\deepnotakto\environment.py:72: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if board == None:


In [13]:
e.board

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])