In [1]:
# General
import sys
import numpy as np
sys.path.insert(0, '..')
# Tree Search
from importlib import reload
import treesearch as ts
import agents.qtree as qtree
import agents.treeactivated as activated
# Notakto
import util
from visual import GameWithConfidences
from environment import Env
from agents.random_agent import RandomAgent
from agents.human import Human

In [ ]:
_ = [reload(i) for i in (qtree, ts, util, activated)]

In [ ]:
params = {"rotate_live": True, "train_live": True, "learn_rate": .005, "batch_size": 10, "replay_size": 50, "epochs": 2}
agent = qtree.QTree([16, 200, 200, 200, 16], params = params, play_simulations = 20, max_queue = 100)

In [25]:
agent = util.load_agent("agents/saves/server_trained_5x5_jan_9.npz", qtree.QTree)

In [ ]:
agent.self_play(10000, 30, train = True, save_every = 50, save_name = "agents/saves/new4_large_1.npz")

In [26]:
agent.iteration

2069

In [27]:
print(util.average_value(agent, n = 1000))

-0.0375561928898


In [33]:
u = util.create_board([], 5)
print(agent.value(u))
print(agent.get_Q(u))
print(agent.raw(u))

1.0
[[ 0.02465669  0.01685563  0.02488299  0.01571609  0.02495188]
 [ 0.01579704  0.02860376  0.02570522  0.02662093  0.01595879]
 [ 0.02729752  0.02361543  0.45535406  0.02625339  0.02552336]
 [ 0.01588583  0.02932447  0.02682067  0.02901184  0.01520666]
 [ 0.02406056  0.01510415  0.02499031  0.01784474  0.02395796]]
[[ 47.34116745   9.0248661    8.64450264   9.0340023    8.57450294
    9.03676701   8.57964039   9.17335606   9.06651211   9.10151577
    8.58982754   9.12661362   8.98171806  11.94089317   9.08761311
    9.059412     8.58524513   9.19824028   9.10899067   9.18752193
    8.54155159   9.00039196   8.53478718   9.03830624   8.70152664
    8.99611855]]


In [34]:
env = Env(5, starting = u)
r = RandomAgent(env)
h = Human()
agent.mode("search")
agent.play_simulations = 20
GameWithConfidences(env, agent, r, show_confidences = True)

SystemExit: 

C:\Users\abeol\Anaconda3\envs\Deep-Notakto\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [11]:
print(agent.get_biases())
print(agent.get_weights())

[array([[  2.19569251e-01,  -4.68724757e-01,   4.38960642e-02,
         -1.51826441e-01,   3.17792296e-01,   2.07468048e-01,
          1.56404898e-01,   1.39102027e-01,  -5.39548695e-02,
          1.90439641e-01,   2.58832306e-01,  -4.50073071e-02,
          3.63908142e-01,   1.72977939e-01,  -4.81505483e-01,
         -1.24016311e-03,  -2.60074258e-01,  -2.55608648e-01,
          1.33076698e-01,  -3.56242210e-01,  -5.19607179e-02,
          1.45157129e-01,  -9.37614590e-02,  -5.20015322e-02,
         -9.60970372e-02,  -1.52921408e-01,  -3.74907672e-01,
          4.56625730e-01,   1.68482378e-01,  -6.85021207e-02,
          3.84430289e-01,   2.16420665e-01,  -1.80602640e-01,
         -1.12567519e-04,  -2.92144299e-01,   1.86375186e-01,
          5.25106966e-01,  -4.86299455e-01,  -3.58809620e-01,
         -4.60869193e-01,   7.00012967e-02,   1.11521043e-01,
         -2.43747845e-01,  -7.91230947e-02,   3.93444210e-01,
          9.90565568e-02,   1.00775994e-01,  -1.16987877e-01,
       