In [1]:
import numpy as np
from copy import copy
from importlib import reload

import environment as env
import visual
import trainer
import agents.random_agent as rp
import agents.Q as Q
import agents.human as human
import agents.activated as activated
import util
import agents.agent as agent
from train import train_agent
# import agents.perfect as perfect

In [8]:
_ = reload(env)
_ = reload(agent)
_ = reload(Q)
_ = reload(visual)
_ = reload(activated)
_ = reload(util)
_ = reload(trainer)

In [2]:
e = env.Env(3)
#a = util.load_agent("agents/saves/Q(05661).npz", Q.Q)
a = activated.ReluHidden([9, 10, 9], gamma = .4, training = {"mode": "episodic", "learn_rate": 1e-3})
d = activated.ReluHidden([9, 10, 9], gamma = .4, training = {"mode": "episodic", "learn_rate": 1e-3})
h = human.Human()
r = rp.RandomAgent(e)

In [3]:
a.mop = True
d.mop = False
gui = visual.GameWithConfidences(e, a, d, show_confidences = True)

-------------------
Action
[[0 0 0]
 [1 0 0]
 [0 0 0]]
Reward        -- -10
Current Value -- 1.2781901819461536
Future        -- 3.7445379083761092
Bellman -- -8.502184836649556
-------------------
Action
[[0 0 0]
 [1 0 0]
 [0 0 0]]
Reward        -- -10
Current Value -- 1.9310363212325499
Future        -- 3.434943040928667
Bellman -- -8.626022783628533


SystemExit: 

C:\Users\abeol\Anaconda3\envs\Deep-Notakto\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [4]:
a.mop = False
d.mop = False
train_agent(e, a, d, 10, 10, False)

Traning Agents 'Q_relu_hidden(fe8d5)' vs 'Q_relu_hidden(2fe82)'
Elapsed 0 : 0 : 0 (at 8 : 43)
Score: 30% vs 70% out of 10 games [1 / 10 rounds played]

Elapsed 0 : 0 : 0 (at 8 : 43)
Score: 0% vs 100% out of 10 games [2 / 10 rounds played]

Elapsed 0 : 0 : 1 (at 8 : 43)
Score: 20% vs 80% out of 10 games [3 / 10 rounds played]

Elapsed 0 : 0 : 1 (at 8 : 43)
Score: 40% vs 60% out of 10 games [4 / 10 rounds played]

Elapsed 0 : 0 : 1 (at 8 : 43)
Score: 40% vs 60% out of 10 games [5 / 10 rounds played]

Elapsed 0 : 0 : 2 (at 8 : 43)
Score: 40% vs 60% out of 10 games [6 / 10 rounds played]

Elapsed 0 : 0 : 2 (at 8 : 43)
Score: 30% vs 70% out of 10 games [7 / 10 rounds played]

Elapsed 0 : 0 : 3 (at 8 : 43)
Score: 30% vs 70% out of 10 games [8 / 10 rounds played]

Elapsed 0 : 0 : 3 (at 8 : 43)
Score: 0% vs 100% out of 10 games [9 / 10 rounds played]

Elapsed 0 : 0 : 3 (at 8 : 43)
Score: 40% vs 60% out of 10 games [10 / 10 rounds played]

