In [1]:
import numpy as np
from importlib import reload
import random
from copy import copy

import environment as env
import visual
import trainer
import agents.random_agent as rp
import agents.Q as Q
import agents.human as human
import agents.activated as activated
import util
import agents.agent as agent
import train
# import agents.perfect as perfect

In [14]:
_ = reload(env)
_ = reload(agent)
_ = reload(Q)
_ = reload(visual)
_ = reload(activated)
_ = reload(util)
_ = reload(trainer)
_ = reload(train)

In [15]:
e = env.Env(3)
params ={"mode": "episodic", "learn_rate": .0004, "rotate": True, "epsilon_func": lambda x: 0,
         "epochs": 1, "batch_size": 1}
#a = Q.Q([9, 10, 9], gamma = .5, training = params, name = "a")
a = util.load_agent("agents/saves/a.npz", Q.Q)
#d = Q.Q([9, 10, 9], gamma = .5, training = params, name = "d")
d = util.load_agent("agents/saves/d.npz", Q.Q)
h = human.Human()
r = rp.RandomAgent(e)

In [18]:
a.mop = False
d.mop = False
a.change_param("rotate", True)
d.change_param("rotate", True)
train.train_agent(e, a, d, 10, 250, save_a1 = True, save_a2 = True, path = "agents/saves/", constant = False)

Traning Agents 'a' vs 'd'
Elapsed 0 : 0 : 34 (at 15 : 58)
Score: 50% vs 50% out of 250 games [1 / 10 rounds played]

Elapsed 0 : 0 : 59 (at 15 : 58)
Score: 50% vs 50% out of 250 games [2 / 10 rounds played]



KeyboardInterrupt: 

In [27]:
a.mop = True
d.mop = True
a.change_param("rotate", False)
d.change_param("rotate", False)
train.train_agent(e, a, d, 1, 1, constant = False)
# gui = visual.GameWithConfidences(e, a, d, -1, show_confidences = True)

Traning Agents 'a' vs 'd'
-------------------
PLAYER :: a
State   Action
[0 0 0]  [0 0 0]
[0 0 0]  [1 0 0]
[0 0 0]  [0 0 0]
Reward        -- 0
Current Value -- 0.5916544795036316
Future        -- 1.1484748125076294
Bellman       -- 0.5742374062538147
Delta         -- -0.017417073249816895
-------------------
PLAYER :: a
State   Action
[0 0 0]  [1 0 0]
[1 0 1]  [0 0 0]
[0 0 0]  [0 0 0]
Reward        -- 0
Current Value -- 0.18170537054538727
Future        -- 1.0554001331329346
Bellman       -- 0.5277000665664673
Delta         -- 0.34599469602108
-------------------
PLAYER :: a
State   Action
[1 1 0]  [0 0 0]
[1 0 1]  [0 0 0]
[0 0 0]  [0 0 1]
Reward        -- 2
Current Value -- 1.0554001331329346
Future        -- -1.516960620880127
Bellman       -- 1.2415196895599365
Delta         -- 0.18611955642700195
-------------------
PLAYER :: a
State   Action
[1 1 0]  [1 0 0]
[1 0 1]  [0 0 0]
[0 1 1]  [0 0 0]
Reward        -- -10
Current Value -- -1.9525991678237915
-------------------
PLAYER :: d


In [28]:
state = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])
move = np.array([
    [0, 0, 0],
    [0, 0, 1],
    [0, 0, 0]
])
a.mop = False
print(a.target(state, move, 0) - a.get_Q(state))

[[ 0.          0.          0.        ]
 [ 0.          0.         -0.01849467]
 [ 0.          0.          0.        ]]


In [ ]:
a.get_weights()