In [2]:
# Dependencies
import random, sys
import numpy as np
from importlib import reload
from copy import copy

# Deepnotakto Project
sys.path.insert(0, '..')
import util, visual, trainer, train, agents.agent
import environment as env
import agents.random_agent as rp
import agents.Q as Q
import agents.human as human
import agents.activated as activated

In [ ]:
_ = reload(env)
_ = reload(agents.agent)
_ = reload(Q)
_ = reload(visual)
_ = reload(activated)
_ = reload(util)
_ = reload(trainer)
_ = reload(train)

In [24]:
e = env.Env(3)
params ={"mode": "episodic", "learn_rate": .005, "rotate": True, "epsilon_func": lambda x: 100 / x,
         "epochs": 1, "batch_size": -1}
a = Q.Q([9, 40, 9], gamma = .5, training = params, name = "a")
#a = util.load_agent("agents/saves/a.npz", Q.Q)
d = Q.Q([9, 20, 9], gamma = .5, training = params, name = "d")
#d = util.load_agent("agents/saves/d.npz", Q.Q)
h = human.Human()
r = rp.RandomAgent(e)

Exception ignored in: <bound method ScopedTFStatus.__del__ of <tensorflow.python.framework.c_api_util.ScopedTFStatus object at 0x00000220038172E8>>
Traceback (most recent call last):
  File "C:\Users\abeol\Anaconda3\envs\Deep-Notakto\lib\site-packages\tensorflow\python\framework\c_api_util.py", line 36, in __del__
    c_api.TF_DeleteStatus(self.status)
AttributeError: 'ScopedTFStatus' object has no attribute 'status'


In [25]:
a.mop = False
d.mop = False
a.change_param("rotate", True)
d.change_param("rotate", True)
a.trainer.iteration = 0
d.trainer.iteration = 0
train.train_agent(e, a, d, 10, 100, save_a1 = True, save_a2 = True, path = "agents/saves/", constant = True)

Traning Agents 'a' vs 'd'
Elapsed 0 : 0 : 4 (at 14 : 17)
Score: 53% vs 47% out of 100 games [1 / 10 rounds played]

Elapsed 0 : 0 : 8 (at 14 : 17)
Score: 48% vs 52% out of 100 games [2 / 10 rounds played]

Elapsed 0 : 0 : 13 (at 14 : 17)
Score: 57% vs 43% out of 100 games [3 / 10 rounds played]

Elapsed 0 : 0 : 18 (at 14 : 17)
Score: 74% vs 26% out of 100 games [4 / 10 rounds played]

Elapsed 0 : 0 : 23 (at 14 : 17)
Score: 64% vs 36% out of 100 games [5 / 10 rounds played]

Elapsed 0 : 0 : 28 (at 14 : 17)
Score: 40% vs 60% out of 100 games [6 / 10 rounds played]

Elapsed 0 : 0 : 33 (at 14 : 17)
Score: 20% vs 80% out of 100 games [7 / 10 rounds played]

Elapsed 0 : 0 : 39 (at 14 : 17)
Score: 19% vs 81% out of 100 games [8 / 10 rounds played]

Elapsed 0 : 0 : 45 (at 14 : 17)
Score: 24% vs 76% out of 100 games [9 / 10 rounds played]

Elapsed 0 : 0 : 52 (at 14 : 17)
Score: 30% vs 70% out of 100 games [10 / 10 rounds played]



In [26]:
a.mop = True
d.mop = False
a.change_param("rotate", False)
d.change_param("rotate", False)
#train.train_agent(e, a, d, 1, 1, constant = False)
gui = visual.GameWithConfidences(e, a, d, -1, show_confidences = True)

-------------------
PLAYER :: a
State   Action
[0 0 0]  [0 1 0]
[0 0 0]  [0 0 0]
[0 0 0]  [0 0 0]
Reward        -- 0
Current Value -- 1.3707469701766968
Future        -- 2.9341883659362793
Bellman       -- 1.4670941829681396
Delta         -- 0.09634721279144287
-------------------
PLAYER :: a
State   Action
[0 1 0]  [0 0 0]
[0 0 0]  [0 0 0]
[0 0 1]  [0 1 0]
Reward        -- 0
Current Value -- 1.1138262748718262
Future        -- 2.0512218475341797
Bellman       -- 1.0256109237670898
Delta         -- -0.08821535110473633
-------------------
PLAYER :: a
State   Action
[0 1 0]  [1 0 0]
[1 0 0]  [0 0 0]
[0 1 1]  [0 0 0]
Reward        -- 2
Current Value -- 1.6144020557403564
Future        -- -0.4948778748512268
Bellman       -- 1.752561092376709
Delta         -- 0.13815903663635254
-------------------
PLAYER :: a
State   Action
[1 1 0]  [0 0 0]
[1 0 1]  [0 0 0]
[0 1 1]  [1 0 0]
Reward        -- -2
Current Value -- -1.6965336799621582


SystemExit: 

C:\Users\abeol\Anaconda3\envs\Deep-Notakto\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
state = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])
move = np.array([
    [0, 0, 0],
    [0, 0, 1],
    [0, 0, 0]
])
a.mop = False
print(a.target(state, move, 0) - a.get_Q(state))

In [ ]:
a.get_weights()

In [ ]:
l = []
q = deque(maxlen = 10)
r1 = range(10000)
r2 = range(10000)
%timeit for i in r1: q.append(i)
%timeit for i in r2: l.append(i)